sudo: false
dist: trusty
language: node_js
node_js:
  - "stable"
services:
  - postgresql
before_script: 
  - npm install
  - psql -c 'drop database if exists travis;' -U postgres
  - psql -c 'CREATE DATABASE travis;' -U postgres
  - psql -c "CREATE USER ann WITH PASSWORD 'secret';" -U postgres
script:
  - npm run test
after_success:
  - npm run coverage
env:
  global: