language: node_js
node_js:
 - "stable"
notifications:
 email: false
cache:
 directories:
   - node_modules
services:
   - postgresql
install:
- npm install
env:
- NODE_ENV=test DB_USERNAME=postgres DB_PASSWORD=Annmary DB_TEST_NAME=weconnectTest secretKey=secret

before_script:
- psql -c 'create database weconnectTest;' -U postgres
- psql -c "CREATE USER annmary WITH PASSWORD 'secret';" -U postgres
script:
 - npm run test

after_success:
 - npm run coverage
#  - npm run report-coverage
#  - npm run coveralls