version: '3'

services:
  web:
    build: .
    ports:
      - "8200:8200"
    env_file: .env
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
      - DB_HOST=$DB_HOST
      - DB_DIALECT=$DB_DIALECT
    links:
       - db
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local


