export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CREATE_BUSINESS_SUCCESSFUL = 'CREATE_BUSINESS_SUCCESSFUL';
export const CREATE_BUSINESS_FAILED = 'CREATE_BUSINESS_FAILED';
export const ADD_BUSINESS = 'ADD_BUSINESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';